version: '3.8'

services:
  comandos_factura:
    volumes:
      - ./comandos_factura/:/app/
    build: ./comandos_factura
    command:
      - sh
      - -c
      - |
        ./wait-for-it.sh db:5432 -- alembic upgrade head
        flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
