version: '3.8'

services:
  comandos_factura:
    volumes:
      - ./comandos_factura/:/app/
    build: ./comandos_factura
    command:
      - sh
      - -c
      - |
        ./wait-for-it.sh db:5432 -- alembic upgrade head
        flask run --host=0.0.0.0 --port=5051
    ports:
      - "5051:5051"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db/postgres

  verificador:
    volumes:
      - ./verificador/:/app/
    build: ./verificador
    command:
      - sh
      - -c
      - |
        ./wait-for-it.sh comandos_factura:5051 -- python --version
        ls
        python listener.py
    depends_on:
      - db
      - comandos_factura
    environment:
      - PYTHONUNBUFFERED=1

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  auth_service:
    volumes:
      - ./auth_service/:/app/
    build: ./auth_service
    command:
      - sh
      - -c
      - |
        flask run --host=0.0.0.0 --port=5002
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db/postgres
      - SECRET_KEY=your_secret_key
      - FLASK_APP=app:create_app

  api_gateway:
    volumes:
      - ./api_gateway/:/app/
    build: ./api_gateway
    command:
      - sh
      - -c
      - |
        flask run --host=0.0.0.0 --port=5053
    ports:
      - "5053:5053"
    depends_on:
      - comandos_factura
    environment:
      - FLASK_APP=app:create_app
      - FACTURAS_SERVICE_URL=http://comandos_factura:5051
